### ISSUE TITLE
Triangular remapping function is not monotonic and results in artifacts

### ISSUE THREAD

**Issue by 10110111** [bartwronski/BlogPostsExtraMaterial#2]
In the [`2ddithering.nb`](https://github.com/bartwronski/BlogPostsExtraMaterial/blob/master/DitheringPostSeries/2ddithering.nb) file, the `remaptri` function yields `-1` for input values of `0` and `1`, while it's expected to return `1` for input `1`. This results in "holes" in the remapped blue noise textures generated by your [BlueNoiseGenerator](https://github.com/bartwronski/BlueNoiseGenerator). See e.g. the following textures:

* Blue noise tiled 5×5 (original from `noise.txt` output file of the generator)
![blue](https://user-images.githubusercontent.com/6376882/112734223-72720800-8f55-11eb-92f1-de77bba8d6f0.png)
* Triangle-remapped version of the noise above
![blue-tri](https://user-images.githubusercontent.com/6376882/112734238-933a5d80-8f55-11eb-92c7-54f14561385a.png)

I propose the following replacement function:
```Mathematica
remaptri[v_] = Piecewise[{{Sqrt[2*v] - 1    , v <= 1/2},
                          {1 - Sqrt[2 - 2*v], v > 1/2}}];
```
This one is monotonic on the whole interval [0, 1], and the output from it looks like the following:
![blue-tri-fixed](https://user-images.githubusercontent.com/6376882/112734314-0cd24b80-8f56-11eb-8c13-d4fbf55e4845.png)

**Comment by bartwronski** [comment]
Thanks for catching the issue, I didn't notice it when writing original code.
Unfortunately I don't own a Mathematica license anymore to modify and test it (I switched to numpy/colab a while ago), but I'll be happy to accept pull requests if you want to fix it. Thank you!
